# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 901f0be18eae282604e2fadb69c939c887d31d2593d741ad8a78f55f923bd008d5620b0a1953bde02a66f84096b7daf066acae35e63b9c6fd6822a36b419ec9e

test:
  secret_key_base: 6ef3e4297a9aedc356d83e734ee71ce7c6360bec32acb582e1a4dcbd4931f79cd878c2d948ad77fe58995afb0cd8a501c66c239a6643d576d657336781ff77d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
